# Generated by Django 5.1.3 on 2024-12-09 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news_categories.newscategory'),
        ),
    ]
